deploy:
  needs: test
  runs-on: ubuntu-latest  # Use GitHub-hosted runner
  steps:
    - name: Download test artifact
      uses: actions/download-artifact@v4
      with:
        name: test-results

    - name: Show test results
      run: cat test-results/results.txt

    - name: Deploy application
      run: |
        echo "Starting deployment..."
        npm install
        npm start &
        echo "Deployment completed."
